services:
  db:
    user: root
    build:
      context: ./databases/PostgreSQL
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: ${DBNAME}
      BACKEND_PASSWORD: ${BACKEND_PASSWORD}
      READER_PASSWORD: ${READER_PASSWORD}
      TEST_DB_NAME: ${TEST_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./databases/PostgreSQL/init.sql:/init.sql
      - ./databases/PostgreSQL/roles.sql:/roles.sql
      - ./databases/PostgreSQL/roots.sql:/roots.sql
    networks:
      - default

  redis:
    container_name: redis_for_bot
    build:
      context: ./databases/Redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis_for_bot_data:/data
      - ./databases/Redis/redis.conf:/redis.conf
    environment:
      REDIS_FOR_BOT_PASSWORD: ${REDIS_FOR_BOT_PASSWORD}
    command: ["sh", "-c", "envsubst < /redis.conf > /tmp/processed_redis.conf && redis-server /tmp/processed_redis.conf"]
    networks:
      - default

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  web:
    container_name: web
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:main --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    environment:
      TOKEN_FOR_GEOSUGGEST: ${TOKEN_FOR_GEOSUGGEST}
      TOKEN_FOR_GEOCODER: ${TOKEN_FOR_GEOCODER}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MENU_COLLECTION: ${MENU_COLLECTION}
      TEST_MENU_COLLECTION: ${TEST_MENU_COLLECTION}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BACKET_NAME: ${S3_BACKET_NAME}
      DBNAME: ${DBNAME}
      TEST_DB_NAME: ${TEST_DB_NAME}
      BACKEND_PASSWORD: ${BACKEND_PASSWORD}
      DEBUG: ${DEBUG}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      BOT_TOKEN: ${BOT_TOKEN}

    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
      - db
    networks:
      - default

  telegram_bot:
    container_name: telegram_bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      REDIS_FOR_BOT_PASSWORD: ${REDIS_FOR_BOT_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - ./bot/bot_api:/bot/bot_api
    ports:
      - "8081:8081"
    command: ["python3", "bot_api/bot.py"]
    depends_on:
      - web # Зависит от бд-шек так как зависит от web
    networks:
      - default

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
     - ./frontend/public:/app/public
     - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - telegram_bot
    command: ["sh", "-c", "npm run build && serve -s build"]
    networks:
      - default

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/certs
      - nginx_log:/etc/nginx/var/log # Пишем логи в том 

    depends_on:
      - frontend
    command: sh -c "nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"
    networks:
      - default
  
  ddns:
    container_name: ddns
    build: 
      context: ./ddns
      dockerfile: Dockerfile
    environment:
      DUCK_TOKEN: ${DUCK_TOKEN}
      TEST: ${TEST}
    depends_on:
      - nginx
    command: ["/bin/bash", "/duckdns/duck.sh"]
    networks:
      - default
      
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  postgres_data:
  redis_for_bot_data:
  mongodb_data:
  nginx_log:
  https_certs:
