services:
  db:
    user: root
    build: 
      context: ./PostgreSQL
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: ${DBNAME}
      BACKEND_PASSWORD: ${BACKEND_PASSWORD} 
      READER_PASSWORD: ${READER_PASSWORD}
      TEST_DB_NAME: ${TEST_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./PostgreSQL/init.sql:/init.sql
      - ./PostgreSQL/roles.sql:/roles.sql
      - ./PostgreSQL/roots.sql:/roots.sql

  redis:
    container_name: redis_for_bot
    build:
      context: ./Redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - redis_for_bot_data:/data
      - ./Redis/redis.conf:/redis.conf
    environment:
      REDIS_FOR_BOT_PASSWORD: ${REDIS_FOR_BOT_PASSWORD}
    command: ["sh", "-c", "envsubst < /redis.conf > /tmp/processed_redis.conf && redis-server /tmp/processed_redis.conf"]

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db




volumes:
  postgres_data:
  redis_for_bot_data:
  mongodb_data:
