(INHERITANCE, NAME, DESCRIPTION, MAIN_PHOTO, PHOTOS, WEBSITE, EXT_SERV_1,
 EXT_SERV_2, EXT_SERV_3, TG_LINK, INST_LINK, VK_LINK,
 ORIG_PHONE, WAPP_PHONE, ADDRESS_CITY, ADDRESS_STREET,
 ADDRESS_HOUSE, ADDRESS_LOCATION, MENU, CATEGORIES) = range(20)
