name: Tests for backend

on:
  push:
    branches:
      - master
    paths: 
      - backend/**

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Install mypy
      run: |
        pip install mypy

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run mypy for backend 
      run: |
        mypy --strict backend
      continue-on-error: true


    - name: Run test for backend
      run: |
        pytest backend
      continue-on-error: true


    