name: Tests for backend

on:
  push:
    branches:
      - "master"
    paths: 
      - "backend/main_app/**"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pwd
        python -m pip install --upgrade pip setuptools
        pip install -r backend/main_app/requirements.txt

    - name: Install mypy
      run: |
        pip install mypy

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run mypy for backend 
      run: |
        mypy --strict main.py


    - name: Run test for backend
      run: |
        pytest backend/main_app/


    
