name: Tests for backend

on:
  push:
    branches:
      - "master"
    paths: 
      - "backend/main_app/**"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        cd backend/main_app/
        pwd
        python3 -m venv venv
        source venv/bin/activate
        ls
        pwd
        pip install -r requirements.txt
        ls
        mypy --strict main.py

    - name: Run test for backend
      run: |
        pytest backend/main_app/


    
