name: Tests for backend

on:
  push:
    branches:
      - master
    paths: 
      - backend/**

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd backend
        cd main_app
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install mypy
      run: |
        pip install mypy

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run mypy for backend 
      run: |
        mypy --strict backend/main_app/


    - name: Run test for backend
      run: |
        pytest


    
