name: Tests for bot

on:
  push:
    branches:
      - master
    paths: 
      - bot/**

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot/bot_api/requirements.txt

    - name: Install mypy
      run: |
        pip install mypy

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run mypy for bot
      run: |
        mypy --strict bot
      continue-on-error: true


    - name: Run test for bot 
      run: |
        pytest bot/tests
      continue-on-error: true


    