name: Tests

on:
  push:
    branches:
      - master
    paths: 
      - backend/**
      - bot/**

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r bot/requirements.txt

    - name: Install mypy
      run: |
        pip install mypy

    - name: Install pytest
      run: |
        pip install pytest

    - name: Get changed files
      id: get_changed_files
      run: |
        echo "::set-output name=changed_files::$(git diff --name-only HEAD^ HEAD | tr '\n' ' ')"

    - name: Run mypy for backend if changed
      if: contains(steps.get_changed_files.outputs.changed_files, 'backend/')
      run: |
        mypy --strict backend

    - name:: Run test for backend if changed
      if: contains(steps.get_changed_files.outputs.changed_files, 'backend/')
      run: |
        pytest backend


    - name: Run mypy for bot if changed
      if: contains(steps.get_changed_files.outputs.changed_files, 'bot/')
      run: |
        mypy --strict bot

    - name:: Run test for bot if changed
      if: contains(steps.get_changed_files.outputs.changed_files, 'bot/')
      run: |
        pytest bot

    